use_frameworks!

platform :ios, '10.0'

target 'GemvaryCloudCallSDK_Example' do
  pod 'GemvaryCloudCallSDK', :path => '../'

  target 'GemvaryCloudCallSDK_Tests' do
    inherit! :search_paths

    
  end
end
